controllers/HomeController.php
<?php

namespace app\controllers;

use \DateTime;
use Yii;
use yii\helpers\Url;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\web\Cookie;
use app\models\LoginForm;
use app\models\ExportForm;
use app\models\ProductOrder;
use yii\data\ActiveDataProvider;
use app\models\Category;
use app\models\Product;
use app\models\Banner;
use app\models\OrderItem;
use yii\web\NotFoundHttpException;

class HomeController extends Controller
{
    // public $enableCsrfValidation = false;

    public function behaviors()
    {
        return [
            'access' => [
            'class' => AccessControl::className(),
            'rules' => [
                    [
                        'actions' => ['login'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['?', '@'],
                    ],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : NULL,
            ],
        ];
    }

    public function actionIndex() {
        return $this->render('index');
    }

    public function actionCart() {
        return $this->render('cart_view');
    }

    public function actionConfirm($code) {

        return $this->render('order_confirm',[
                'code' => $code
        ]);
    }

    public function actionContact() {

        return $this->render('contact');
    }    

    public function actionOrder() {
        $model = new ProductOrder();
        $products = Yii::$app->cart->getPositions();


        if ($model->load(Yii::$app->request->post())) {
            if($model->save()) {
                foreach ($products as $product) {
                    $order_item = new OrderItem();
                    $order_item->order_id = $model->id;
                    $order_item->product_id  =  $product->id;
                    $order_item->quantity  =  $product->getQuantity();
                    $order_item->price  =  $product->getCost();
                    $order_item->discounted_price  =  $product->getCost(true);
                    $order_item->save();
                }
                Yii::$app->cart->removeAll();
                return Yii::$app->response->redirect(Url::to(['/home/confirm/', 'code' => $model->code]));
            }
        }

        return $this->render('order_info',[
                'model' => $model
            ]);
    }

    public function actionItem($id) {
        if (($model = Product::findOne($id)) !== null) {
            return $this->render('product_detail', [
                    'model' => $model
                ]);
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionCategory($id) {
        if (($category = Category::findOne($id)) !== null) {
            $dataProvider = new ActiveDataProvider([
                'query' => $category->getProducts(SORT_DESC),
                'pagination' => [
                    'pageSize' => 36
                ]
            ]);
            return $this->render('product_list', [
                    'category' => $category,
                    'dataProvider' => $dataProvider
                ]);
        }
        throw new NotFoundHttpException('The requested page does not exist.');

    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionAddToCart($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            Yii::$app->cart->put($model, Yii::$app->request->post('quantity'));
            return true;
        }
        return false;
    }


    public function actionRemoveFromCart($id)
    {
        Yii::$app->cart->removeById($id);
        return true;
    }

    public function actionSearch()
    {
        $query = Yii::$app->request->get('query');
        $order = ProductOrder::findOne(['code' => $query]);
        if ($order) {
            return $this->render('view_order',[
                'order' => $order
            ]);
        } else {
            $dataProvider = new ActiveDataProvider([
                'query' => Product::find()
                            ->where(['like', 'name', $query])
                            ->orWhere(['like', 'description', $query]),
                'pagination' => [
                    'pageSize' => 36
                ]
            ]);
            return $this->render('product_list', [
                    'dataProvider' => $dataProvider
            ]);
        }
    }

    public function actionLanguage()
    {
        $language = Yii::$app->request->post('language');
        Yii::$app->language = $language;

        $languageCookie = new Cookie([
            'name' => 'language',
            'value' => $language,
            'expire' => time() + 60 * 60 * 24 * 30, // 30 days
        ]);
        Yii::$app->response->cookies->add($languageCookie);
        // return Yii::$app->language;
        return Yii::$app->response->redirect(Yii::$app->request->referrer);
    }

}

controllers/ProfileController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use app\models\User;

class ProfileController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
            'class' => AccessControl::className(),
            'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
    	$user = Yii::$app->user->identity;
        return $this->render('index', [ 'model' => $user ]);
    }

    public function actionUpdate()
    {
    	$model = Yii::$app->user->identity;
        $model->scenario = User::SCENARIO_UPDATE_PROFILE;

        if ($model->load(Yii::$app->request->post())) {

            if(!empty($model->_password)) {
                $model->setPassword($model->_password);
            }
            if($model->save()) {
            	return $this->redirect(['index']);
            }
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }
}

views/layouts/admin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AdminAsset;

AdminAsset::register($this);

$isAdmin = !Yii::$app->user->isGuest && Yii::$app->user->identity->getRole() === "administrator";
$isAuthenticated = !Yii::$app->user->isGuest;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'GAMERSHOP',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            [
                'label' => 'Management',
                'items' => [
                    [
                        'label' => 'Users',
                        'url' => ['/admin/user/index'],
                        'visible' => $isAdmin
                    ],

                    [
                        'label' => 'Categories',
                        'url' => ['/admin/category/index'],
                        'visible' => $isAdmin
                    ],

                    [
                        'label' => 'Products',
                        'url' => ['/admin/product/index'],
                        'visible' => $isAdmin
                    ],

                    [
                        'label' => 'Promotions',
                        'url' => ['/admin/promotion/index'],
                        'visible' => $isAdmin
                    ],
                    [
                        'label' => 'Orders',
                        'url' => ['/admin/order/index'],
                        'visible' => $isAdmin
                    ],
                    [
                        'label' => 'Banners',
                        'url' => ['/admin/banner/index'],
                        'visible' => $isAdmin
                    ]

                ],
                'visible' => $isAdmin
            ],
            ['label' => 'Profile', 'url' => ['/profile/index'], 'visible' => $isAuthenticated],
            $isAuthenticated ?
                [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/home/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ] :
                ['label' => 'Login', 'url' => ['/home/login']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; TheITFox <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\models\Category;

AppAsset::register($this);

$isAdmin = !Yii::$app->user->isGuest && Yii::$app->user->identity->getRole() === "administrator";
$isAuthenticated = !Yii::$app->user->isGuest;
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <?php $this->head() ?>
</head>
<body class="main">
    <div id="fb-root"></div>
    <script>
        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <?php $this->beginBody() ?>
    <div class="container">
        <div class="row" id="top">
            <div class="">  
                <div class="row" id="uptop">
                    <div class="col-md-12 clearfix">
                        <p class="pull-left">Hotline: 0979-077-067</p>
                        <div class="pull-right top-right">
                            <a class="cart-link" href="/home/cart">
                                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"><span class="badge"><?= sizeof(Yii::$app->cart->getPositions()) ?></span></span>
                            </a>
                            <?= Html::beginForm('/home/language') ?>   
                            <?= Html::dropDownList('language', Yii::$app->language, ['en_GB' => 'EN', 'vi' => 'VI'], ['onchange'=>'this.form.submit()']) ?>
                            <?= Html::endForm() ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/">GAMERSHOP</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" role="navigation">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?= Yii::t('main', 'Products') ?></a>
                                <ul class="dropdown-menu" role="menu">
                                    <? foreach (Category::find()->where(['parent_id' => null])->all() as $category): ?>
                                    <?
                                        $children = $category->children;
                                        $hasChildren = count($children) > 0;
                                    ?>
                                    <? if($hasChildren): ?>
                                        <li class="dropdown-submenu">
                                            <? if ($category->name !== "Other"): ?>
                                                <a href="/home/category/<?= $category->id ?>" class="dropdown-toggle" ><?= $category->name ?></a>
                                            <? endif; ?>
                                            <ul class="dropdown-menu" role="menu">
                                                <? foreach ($children as $child): ?>
                                                    <li><a href="/home/category/<?= $child->id ?>"><?= $child->name ?></a></li>
                                                <? endforeach; ?>
                                            </ul>
                                        </li>
                                    <? else: ?>
                                        <? if ($category->name !== "Other"): ?>
                                            <li><a href="/home/category/<?= $category->id ?>"><?= $category->name ?></a></li>
                                        <? endif; ?>
                                    <? endif;?>
                                    <? endforeach; ?>
                                    <? $other = Category::find()->where(["name" => "Other"])->one(); ?>
                                    <? if ($other !== NULL): ?>
                                        <li><a href="/home/category/<?= $other->id ?>"><?= $other->name ?></a></li>
                                    <? endif; ?>
                                </ul>
                            </li>
                            <li><a href="/home/contact"><?= Yii::t('main', 'Contact') ?></a></li>
                        </ul>
                        <form class="navbar-form navbar-right" role="search" action="/home/search" method="GET">
                            <div class="input-group">
                                <input name="query" type="text" class="form-control" placeholder="<?= Yii::t('main', 'Search') ?>">
                                <span class="input-group-btn"><button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button></span>
                            </div>
                        </form>
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div class="container">
    <?= $content ?>
    </div>

    <!-- Footer -->
    <div class="container">
    <div class="row">
        <footer class="footer">
            <div class="container-fluid">
                <div class="col-md-6">
                    <h2>Footer</h2>
                </div>
                <div class="col-md-3">
                    <div class="col-md-6">
                        <div class="panel panel-default footer-panel">
                            <div class="panel-body">
                                <span class="glyphicon glyphicon-road"></span>
                            </div>
                        </div>
                    </div>
                    <h4>National Delivery</h4>
                </div>
                <div class="col-md-3">
                    <div class="col-md-6">
                        <div class="panel panel-default footer-panel">
                            <div class="panel-body">
                                <span class="glyphicon glyphicon-open"></span>
                            </div>
                        </div>
                    </div>
                    <h4>Upgrade<br/>Support</h4>
                </div>
            </div>
        </footer>
    </div>
    </div>

    <!-- Chat -->
    <div class="row">
            <div class="col-md-4 col-md-offset-8">
                <div class="panel panel-default chat">
                    <div class="panel-heading" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                        <h3 class="panel-title"><?= Yii::t('main', 'Chat with us') ?></h3>
                    </div>
                    <div class="collapse" id="collapseExample">
                        <div class="panel-body fb-page" data-href="https://www.facebook.com/Gamer-Shop-167156100332320/" data-tabs="messages" data-width="300" data-height="400" data-small-header="true" data-adapt-container-width="false" data-hide-cover="true" data-show-facepile="true">
                            <div class="fb-xfbml-parse-ignore">
                                <blockquote cite="https://www.facebook.com/Gamer-Shop-167156100332320/">
                                    <a href="https://www.facebook.com/Gamer-Shop-167156100332320/">Gamer Shop</a>
                                </blockquote>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $('.carousel').carousel({
            interval: 3000
        })
    </script>
  <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>