controllers/HomeController.php
<?php

namespace app\controllers;

use \DateTime;
use Yii;
use yii\helpers\Url;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\web\Cookie;
use app\models\LoginForm;
use app\models\ExportForm;
use app\models\ProductOrder;
use yii\data\ActiveDataProvider;
use app\models\Category;
use app\models\Product;
use app\models\Banner;
use app\models\OrderItem;
use yii\web\NotFoundHttpException;

class HomeController extends Controller
{
    // public $enableCsrfValidation = false;

    public function behaviors()
    {
        return [
            'access' => [
            'class' => AccessControl::className(),
            'rules' => [
                    [
                        'actions' => ['login'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['?', '@'],
                    ],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : NULL,
            ],
        ];
    }

    public function actionIndex() {
        return $this->render('index');
    }

    public function actionCart() {
        return $this->render('cart_view');
    }

    public function actionConfirm($code) {

        return $this->render('order_confirm',[
                'code' => $code
        ]);
    }

    public function actionContact() {

        return $this->render('contact');
    }    

    public function actionOrder() {
        $model = new ProductOrder();
        $products = Yii::$app->cart->getPositions();


        if ($model->load(Yii::$app->request->post())) {
            if($model->save()) {
                foreach ($products as $product) {
                    $order_item = new OrderItem();
                    $order_item->order_id = $model->id;
                    $order_item->product_id  =  $product->id;
                    $order_item->quantity  =  $product->getQuantity();
                    $order_item->price  =  $product->getCost();
                    $order_item->discounted_price  =  $product->getCost(true);
                    $order_item->save();
                }
                Yii::$app->cart->removeAll();
                return Yii::$app->response->redirect(Url::to(['/home/confirm/', 'code' => $model->code]));
            }
        }

        return $this->render('order_info',[
                'model' => $model
            ]);
    }

    public function actionItem($id) {
        if (($model = Product::findOne($id)) !== null) {
            return $this->render('product_detail', [
                    'model' => $model
                ]);
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionCategory($id) {
        if (($category = Category::findOne($id)) !== null) {
            $dataProvider = new ActiveDataProvider([
                'query' => $category->getProducts(SORT_DESC),
                'pagination' => [
                    'pageSize' => 36
                ]
            ]);
            return $this->render('product_list', [
                    'category' => $category,
                    'dataProvider' => $dataProvider
                ]);
        }
        throw new NotFoundHttpException('The requested page does not exist.');

    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionAddToCart($id)
    {
        if (($model = Product::findOne($id)) !== null) {
            Yii::$app->cart->put($model, Yii::$app->request->post('quantity'));
            return true;
        }
        return false;
    }


    public function actionRemoveFromCart($id)
    {
        Yii::$app->cart->removeById($id);
        return true;
    }

    public function actionSearch()
    {
        $query = Yii::$app->request->get('query');
        $order = ProductOrder::findOne(['code' => $query]);
        if ($order) {
            return $this->render('view_order',[
                'order' => $order
            ]);
        } else {
            $dataProvider = new ActiveDataProvider([
                'query' => Product::find()
                            ->where(['like', 'name', $query])
                            ->orWhere(['like', 'description', $query]),
                'pagination' => [
                    'pageSize' => 36
                ]
            ]);
            return $this->render('product_list', [
                    'dataProvider' => $dataProvider
            ]);
        }
    }

    public function actionLanguage()
    {
        $language = Yii::$app->request->post('language');
        Yii::$app->language = $language;

        $languageCookie = new Cookie([
            'name' => 'language',
            'value' => $language,
            'expire' => time() + 60 * 60 * 24 * 30, // 30 days
        ]);
        Yii::$app->response->cookies->add($languageCookie);
        // return Yii::$app->language;
        return Yii::$app->response->redirect(Yii::$app->request->referrer);
    }

}

views/home/_order_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\ProductOrder;

/* @var $this yii\web\View */
/* @var $model app\models\ProductOrder */
/* @var $form yii\widgets\ActiveForm */
$model->status = ProductOrder::STATUS_ACTIVE;
?>

<div class="product-order-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'customer_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'note')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'payment_method')->dropDownList([ProductOrder::PAYMENT_COD => 'COD', ProductOrder::PAYMENT_TRANSFER => 'TRANSFER']) ?>

    <div class="form-group pull-right">
        <?= Html::submitButton(Yii::t('order', 'Confirm'), ['class' => 'btn btn-lg proceed']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/home/_product_home_view.php
<div class="col-md-4">
    <a href="/home/item/<?= $model->id?>" class="product-link">
        <div class="thumbnail">
        	<div class="product-item">
            	<img src="<?= $model->getImageUrl('feature_image_1') ?>" alt="..."/>
            </div>
            <div class="caption product-description">
                <h3><?= $model->name ?></h3>
                <? $hasPromotion = $model->promotion !== null ?>
                <p style="<?= $hasPromotion ? "text-decoration: line-through; color: #666;" : ""?>"><?= number_format($model-> price) ?> VND</p>
                <? if ($hasPromotion): ?>
                    <p class="discounted-price" style="color: #169A16; font-weight: bolder;"><?= number_format($model-> getPrice(true)) ?> VND</p>
                <? endif; ?>
            </div>
        </div>
    </a>
</div>

views/home/_product_view.php
<div class="col-md-3">
    <a href="/home/item/<?= $model->id?>" class="product-link">
        <div class="thumbnail">
        	<div class="product-item">
            	<img src="<?= $model->getImageUrl('feature_image_1') ?>" alt="..."/>
            </div>
            <div class="caption product-description">
                <h3><?= $model->name ?></h3>
                <? $hasPromotion = $model->promotion !== null ?>
                <p style="<?= $hasPromotion ? "text-decoration: line-through; color: #666;" : ""?>"><?= number_format($model-> price) ?> VND</p>
                <? if ($hasPromotion): ?>
                    <p class="discounted-price" style="color: #169A16; font-weight: bolder;"><?= number_format($model-> getPrice(true)) ?> VND</p>
                <? endif; ?>
            </div>
        </div>
    </a>
</div>

views/home/cart_view.php
<?
$products = Yii::$app->cart->getPositions();
$this->title = 'Gamershop | View Cart';

?>

<div class="row">
	<ul class="order-steps">
		<li><span class="active">1</span><?= Yii::t('cart', 'Verify Cart') ?></li>
		<li><span>2</span><?= Yii::t('cart', 'Provide Information & Confirm Order') ?></li>
    <li><span>3</span><?= Yii::t('cart', 'Receive Order Code') ?></li>
	</ul>
  <? if(sizeof($products) !== 0): ?>
  	<table class="table cart-table">
  		<tr>
      		<th><?= Yii::t('cart', 'Product') ?></th>
      		<th><?= Yii::t('cart', 'Description') ?></th>
      		<th><?= Yii::t('cart', 'Quantity') ?></th>
          <th><?= Yii::t('cart', 'Amount') ?></th>
          <th></th>
      </tr>
  <!--   		<tr>
      		<td><img src="/images/5.png" alt="..."/></td>
      		<td>Steelseries Stratus XL</td>
      		<td>1
      			
      			<div class="qty_box">
    					<i id="qty_down"> - </i>
    					<i id="qty_val"> 1 </i>
    					<i id="qty_up"> + </i>
    				</div>
      		</td>
      		<td>1.290.000 vnd</td>
      		<td><span class="glyphicon glyphicon-trash cart-delete-icon" aria-hidden="true"></span></td>
    		</tr> -->
        <? foreach ($products as $product): ?>
    		<tr>
      		<td><img src="<?= $product->getImageUrl('feature_image_1'); ?>" alt="..."/></td>
      		<td><?= $product->name ?></td>
      		<td><?= $product->getQuantity()?></td>
      		<td><?= number_format($product->getCost(true)) ?> VND</td>
      		<td><span data-item-id="<?= $product->id ?>" class="glyphicon glyphicon-trash cart-delete-icon btn-rm-cart" aria-hidden="true"></span></td>
    		</tr>
        <? endforeach; ?>
  	</table>

  	<div class="row">
  		<div class="col-md-6 col-md-offset-6">
  			<table class="table">
  				<tr class="total">
  	    		<th><?= Yii::t('cart', 'Total') ?>:</th>
  	    		<th><?= number_format(Yii::$app->cart->getCost(true)) ?> VND</th>
  	    		<th></th>
  	  		</tr>
  		  </table>
  		  	<div class="col-md-4 pull-right">
  			  	<a href="/home/order"><button type="button" class="btn btn-lg pull-right" id="proceed"><?= Yii::t('cart', 'Proceed') ?></button></a>
  			  </div>
  		</div>
  	</div>
  <? else: ?>
    <div class="row">
      <div class="col-md-4 col-md-offset-1">
        <h3><?= Yii::t('cart', 'Cart is empty') ?><br/><br/></h3>
      </div>
    </div>
  <? endif; ?>

</div>

<?
$js = <<<EOT
$('.btn-rm-cart').click(function() {
  itemId = $(this).data('item-id');
  var csrfToken = $('meta[name="csrf-token"]').attr("content");
  $.post('/home/remove-from-cart/' + itemId, {_csrf : csrfToken}, function(data) {
    location.reload();
  }, "json");
}); 
EOT;
$this->registerJs($js, $this::POS_READY);
?>

views/home/contact.php
<? $this->title = 'Gamershop | Contact'; ?>
<h1><?= Yii::t('contact', 'Our Bank Accounts Information') ?></h1>
<div class="row">
	<div class="col-md-6">
		<div class="panel panel-default bank">
			<div class="panel-body">
				<img src="/images/ACB.png" style="width:250px; height:auto"/>
				<p class="bank-detail"><?= Yii::t('contact', 'Account Owner: ') ?>Trần Kim Hoàng </p>
				<p class="bank-detail"><?= Yii::t('contact', 'Account Number: ') ?>113670249</p>
				<p class="bank-detail"><?= Yii::t('contact', 'Bank Address: ') ?>ACB chi nhánh Minh Châu TPHCM</p>
			</div>
		</div>
	</div>
</div>
<p><?= Yii::t('contact', 'If you have any question, please contact us via our ') ?> <span class="text-danger"><?= Yii::t('contact', 'hotline: ') ?>0979 077 067</span></p>

views/home/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/home/index.php
<?
use yii\widgets\ListView;
use yii\data\ActiveDataProvider;
use app\models\Category;
use app\models\Banner;

$this->title = 'Gamershop | Home';
?>

<? function renderImage($model, $index) { ?>
    <? if ($model->status = Banner::STATUS_ACTIVE): ?>
        <div class="item <?= $index==0 ? "active" : "" ?>" > 
            <img src="<?= $model->getImageUrl(); ?>" alt="<?= $model->name ?>"/>
        </div>
    <? endif; ?>
<? } ?>

<? function renderImageIndicators($model, $index) { ?>
    <? if ($model->status = Banner::STATUS_ACTIVE): ?> 
    <li data-target="#main-carousel" data-slide-to="<?= $index ?>" class="<?= $index == 0 ? "active" : "" ?>"></li>
    <? endif; ?>
<? } 
?>
<!-- Carousel -->
<div class="row">
    <div class="bs-example">
        <div id="main-carousel" class="carousel slide" data-ride="carousel">
            <? $banners = Banner::find()->where(['status' => Banner::STATUS_ACTIVE])->all(); ?>

            <!-- Carousel indicators -->
            <ol class="carousel-indicators">
                <? for ($i=0; $i < count($banners); $i++) { 
                    $banner = $banners[$i];
                    echo renderImageIndicators($banner, $i);
                }?>
            </ol>   
            <!-- Wrapper for carousel items -->
            <div class="carousel-inner">
                <? for ($i=0; $i < count($banners); $i++) { 
                    $banner = $banners[$i];
                    echo renderImage($banner, $i);
                }?>
            </div>
            <!-- Carousel controls -->
            <a class="carousel-control left" href="#main-carousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="carousel-control right" href="#main-carousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

<!-- Products -->
<div class="row">
    <div class="panel panel-default index-panel">
        <? foreach (Category::find()->where(['parent_id' => null])->all() as $category): ?>
        <? if ($category->name !== "Other"): ?>
        <?
            $dataProvider = new ActiveDataProvider([
                'query' => $category->getProducts(SORT_DESC),
                'pagination' => [
                    'pageSize' => $category->num_items
                ]
            ]);
        ?>
        <div class="panel-heading">
            <a href="/home/category/<?= $category->id ?>" class="panel-title"><?= $category->name ?></a>
        </div>
        <div class="panel-body">
            <?= ListView::widget([
                'dataProvider' => $dataProvider,
                'itemView' => '_product_home_view',
                'layout' =>
<<<EOT
<div class="row">
{items}
</div>
<div class="product-pager clearfix">
{pager}
</div>
EOT
                ]); ?>
        </div>
        <? endif; ?>
        <? endforeach; ?>
        <? $other = Category::find()->where(["name" => "Other"])->one(); ?>
        <?
            $dataProvider = new ActiveDataProvider([
                'query' => $other->getProducts(SORT_DESC),
                'pagination' => [
                    'pageSize' => $other->num_items
                ]
            ]);
        ?>
        <div class="panel-heading">
            <a href="/home/category/<?= $other->id ?>" class="panel-title"><?= $other->name ?></a>
        </div>
        <div class="panel-body">
            <?= ListView::widget([
                'dataProvider' => $dataProvider,
                'itemView' => '_product_home_view',
                'layout' =>
<<<EOT
<div class="row">
{items}
</div>
<div class="product-pager clearfix">
{pager}
</div>
EOT
                ]); ?>
        </div>
    </div>
</div>

views/home/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username') ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>

views/home/order_confirm.php
<?php

use yii\helpers\Html;
/* @var $this yii\web\View */
use app\models\ProductOrder;
$this->title = 'Gamershop | Confirm Order';

?>

<div class="row">
	<ul class="order-steps">
		<li><span>1</span><?= Yii::t('cart', 'Verify Cart') ?></li>
		<li><span>2</span><?= Yii::t('cart', 'Provide Information & Confirm Order') ?></li>
    <li><span class="active">3</span><?= Yii::t('cart', 'Receive Order Code') ?></li>
	</ul>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-success order-success">
      <div class="panel-heading">
        <h3 class="panel-title"><?= Yii::t('order', 'Order successfully recorded') ?></h3>
      </div>
      <div class="panel-body">
        <span style="font-size: 20px;"><?= Yii::t('order', 'Order Code') ?>: <span style="font-weight: bold;"><?= $code ?></span></span><br/><br/>
        <?= Yii::t('order', 'Enter this code to the search bar to track your order.') ?>
      </div>
    </div>
  </div>
</div>

views/home/order_info.php
<?php

use yii\helpers\Html;
/* @var $this yii\web\View */
use app\models\ProductOrder;
$this->title = 'Gamershop | Order Information';

?>

<?
$products = Yii::$app->cart->getPositions();
?>

<div class="row">
    <ul class="order-steps">
        <li><span>1</span><?= Yii::t('cart', 'Verify Cart') ?></li>
        <li><span class="active">2</span><?= Yii::t('cart', 'Provide Information & Confirm Order') ?></li>
        <li><span>3</span><?= Yii::t('cart', 'Receive Order Code') ?></li>
    </ul>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="row">
        <div class="col-md-6">
        <div class="panel panel-default order-panel">
          <div class="panel-heading">
            <h3 class="panel-title"><?= Yii::t('order', 'Cart Information') ?></h3>
          </div>
          <div class="well">
            <div class="panel-body">
              <table class="table cart-info">
              <? foreach ($products as $product): ?>
                <tr>
                  <td class="pull-left"><?= $product->getQuantity()?></td>
                  <td class="pull-left"> x </td>
                  <td class="pull-left"><?= $product->name ?></td>
                  <td><?= number_format($product->getCost(true)) ?> VND</td>
                </tr>
              <? endforeach; ?>
              </table>
              <table class="table cart-info">
                        <tr class="info-total">
                          <th class="pull-left"><?= Yii::t('cart', 'Total') ?>:</th>
                          <th><?= number_format(Yii::$app->cart->getCost(true)) ?> VND</th>
                      </tr>
              </table>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="panel panel-default order-panel"> 
          <div class="panel-heading">
            <h3 class="panel-title"><?= Yii::t('order', 'Customer Information') ?></h3>
          </div>
          <div class="well">
            <div class="panel-body">
              <?= $this->render('_order_form', [
                'model' => $model,
              ]) ?>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

views/home/product_detail.php
<?php

use yii\helpers\Html;
use app\models\Product;
$this->title = 'Gamershop | Product Detail';

/* @var $this yii\web\View */
/* @var $model app\models\Category */
/* @var $form yii\widgets\ActiveForm */
?>
<? function renderImage($model, $index, $attribute) { ?>
	<? if (!empty($model->$attribute)): ?> 
		<div class="item <?= $index==0 ? "active" : "" ?>" > 
			<img src="<?= $model->getImageUrl($attribute); ?>" alt="<?= $model->name ?>"/>
		</div>
	<? endif; ?>
<? } ?>

<? function renderImageThumbnail($model, $index, $attribute) { ?>
	<? if (!empty($model->$attribute)): ?> 
	<li data-target="#product-carousel" data-slide-to="<?= $index ?>" class="<?= $index == 0 ? "active" : "" ?>">
		<div class="thumbnail"> 
			<img src="<?= $model->getImageUrl($attribute); ?>" alt="<?= $model->name ?>"/>
		</div>
	</li>
	<? endif; ?>
<? } 
?>

<div class="row">
	<div class="row">
		<div class="col-md-6">
			<div class="bs-example">
    			<div id="product-carousel" class="carousel slide item-carousel" data-ride="carousel">
		        	<!-- Wrapper for carousel items -->
		        	<div class="carousel-inner">
		        		<? for ($i=1; $i < 6; $i++) { 
		        			$attribute = 'feature_image_' . $i;
		        			echo renderImage($model, $i-1, $attribute);
		        		}?>
		        	</div>
		        	<!-- Carousel indicators -->
		        	<ol class="carousel-indicators">
		        		<? for ($i=1; $i < 6; $i++) { 
		        			$attribute = 'feature_image_' . $i;
		        			echo renderImageThumbnail($model, $i-1, $attribute);
		        		}?>
		        	</ol>   
		        </div>
			</div>
		</div>
		<div class="col-md-6">
			<div id="item-panel" class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title"><?= $model->name ?></h2>
					</div>
					<div class="panel-body">
						<? $hasPromotion = $model->promotion !== null ?> 
						<div class="price"><h2 style="<?= $hasPromotion ? "text-decoration: line-through; color: #666;" : ""?>"><?= number_format($model->price) ?> VND</h2>
							<? if ($hasPromotion): ?>
	                    		<h2 class="discounted-price" style="color: #169A16; font-weight: bolder;"><?= number_format($model-> getPrice(true)) ?> VND</h2>
	                		<? endif; ?>
                		</div>
						<div class="p_info">
							<div class="p_detail">
								<?= $model->description ?>
							</div>
							<div class="qty_box">
								<i id="qty_down"> - </i>
								<i id="qty_val"> 1 </i>
								<i id="qty_up"> + </i>
							</div>
							<div class="add">
								<button type="button" data-item-id="<?= $model->id ?>" class="btn btn-danger btn-lg btn-cart">Add to cart</button>
							</div>
						</div>
					</div>
			</div>
		</div>
	</div>
</div>

<?
$js = <<<EOT
$('i#qty_down').click(function(){
	var val = parseInt($('i#qty_val').html(), 10);
	if(isNaN(val)) {
		val = 1;
	}
	val--;
	if(val <= 0) {
		val = 1;
	}
	$('i#qty_val').html(val);
});
$('i#qty_up').click(function(){
	var val = parseInt($('i#qty_val').html(), 10);
	if(isNaN(val)) {
		val = 1;
	}
	val++;
	$('i#qty_val').html(val);
});
$('.btn-cart').click(function() {
	itemId = $(this).data('item-id');
	var csrfToken = $('meta[name="csrf-token"]').attr("content");
	$.post('/home/add-to-cart/' + itemId, {_csrf : csrfToken, quantity : $('i#qty_val').html()}, function(data) {
		location.reload();
	}, "json");
}); 
EOT;
$this->registerJs($js, $this::POS_READY);
?>

views/home/product_list.php
<?
use yii\widgets\ListView;
use yii\data\ActiveDataProvider;
use app\models\Category;

$this->title = 'Gamershop | Product List';

?>

<div class="row">
    <div class="panel panel-default product-panel">
        <? //foreach (Category::find()->where(['parent_id' => null])->all() as $category): ?>
    
        <div class="panel-heading">
            <? if (isset($category) && $category != null): ?>
            <a href="#" class="panel-title"><?= $category->name ?></a>
            <? else: ?>
            <span class="panel-title">Results:</span>
            <? endif ?>

        </div>
        <div class="panel-body">
            <?= ListView::widget([
                'dataProvider' => $dataProvider,
                'itemView' => '_product_view',
                'layout' =>
<<<EOT
<div class="row">
{items}
</div>
<div class="product-pager clearfix" style="text-align: center;">
{pager}
</div>
EOT
                ]); ?>
        </div>
    </div>
</div>

views/home/view_order.php
<?
$items = $order->items;
$total = 0;
?>

<h2><span style="color:#2F752F; font-weight:bold;"><?= Yii::t('order', 'Order: {order_code}', ['order_code' => $order->code]) ?></span></h2><br/>

<table class="table cart-table">
	<tr>
  		<th><?= Yii::t('order', 'Product Name') ?></th>
  		<th><?= Yii::t('order', 'Quantity') ?></th>
      <th><?= Yii::t('order', 'Price') ?></th>
      <th><?= Yii::t('order', 'Discounted Price') ?></th>
  </tr>

    <? foreach ($items as $item): ?>
  		<tr>
    		<td><?= $item->product->name ?></td>
    		<td><?= $item->quantity?></td>
    		<td><?= number_format($item->price) ?> VND</td>
        <td><?= number_format($item->discounted_price) ?> VND</td>
  		</tr>
      <? $total+=$item->discounted_price ?>
    <? endforeach; ?>
</table>

<div class="row">
	<div class="col-md-6 col-md-offset-6">
		<table class="table">
			<tr class="total">
    		<th><?= Yii::t('cart', 'Total') ?>:</th>
    		<th><?= number_format($total) ?> VND</th>
    		<th></th>
  		</tr>
	  </table>
</div>