modules/admin/controllers/CategoryController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Category;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class CategoryController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
            'class' => AccessControl::className(),
            'rules' => [
                    [
                        'allow' => false,
                        'verbs' => ['GET'],
                        'actions' => ['delete', 'delete-timer']
                    ],
                    [
                        'allow' => true,
                        'roles' => ['administrator'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Category models.
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'categories' => Category::find()->where(['parent_id' => null])->all(),
        ]);
    }

    /**
     * Displays a single Category model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Category();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Category model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Category model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Category model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Category the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Category::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/admin/views/category/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\models\Category;

/* @var $this yii\web\View */
/* @var $model app\models\Category */
/* @var $form yii\widgets\ActiveForm */
$parents = ["" => ""];
foreach (ArrayHelper::map(Category::find()->where(['parent_id' => null])->all(), 'id', 'name') as $key => $value) {
    $parents[$key] = $value;
}
?>

<div class="category-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'parent_id')->dropDownList($parents) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->dropDownList([Category::STATUS_ACTIVE => 'ACTIVE', Category::STATUS_INACTIVE => 'INACTIVE']) ?>

    <?= $form->field($model, 'is_feature')->checkbox()?>

	<?= $form->field($model, 'num_items')->label(Yii::t('category', "Number of lines shown on home page"))->dropDownList([3=>1,6=>2,9=>3,12=>4,15=>5,18=>6,21=>7]) ?>    

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/category/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = 'Create Category';
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/category/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Category;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('category', 'Categories');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Category', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th><?= Yii::t('category', 'Name') ?></th>
                <th><?= Yii::t('category', 'Status') ?></th>
                <th style="min-width: 120px;"></th>
            </tr>
        </thead>
        <tbody>
            <? $counter = 1 ?>
            <? foreach ($categories as $index => $category): ?>
                <tr>
                    <td><?= $counter ?></td>
                    <td><?= $category->name ?></td>
                    <td><?= $category->status == Category::STATUS_ACTIVE ? 'ACTIVE' : 'INACTIVE' ?></td>
                    <td class="text-center">
                        <div class="btn-group">
                            <?= Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['category/view', 'id' => $category->id], [
                                    'class' => 'btn btn-sm btn-primary',
                                    'data' => [
                                    ]
                                ]); ?>
                            <?= Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['category/update', 'id' => $category->id], [
                                    'class' => 'btn btn-sm btn-success',
                                    'data' => [
                                    ]
                                ]); ?>
                            <?= Html::a('<span class="glyphicon glyphicon-trash"></span>', ['category/delete', 'id' => $category->id], [
                                    'class' => 'btn btn-sm btn-danger',
                                    'data' => [
                                        'method' => 'post',
                                        'confirm' => 'Do you want to delete this item?'
                                    ]
                                ]); ?>
                        </div>
                    </td>
                </tr>
                <?
                    $counter++;
                    $children = $category->children;
                ?>
                <? foreach ($children as $child_index => $child): ?>
                    <tr>
                        <td><?= $counter ?></td>
                        <td> ---- <?= $child->name ?></td>
                        <td><?= $child->status == Category::STATUS_ACTIVE ? 'ACTIVE' : 'INACTIVE' ?></td>
                        <td class="text-center">
                            <div class="btn-group">
                                <?= Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['category/view', 'id' => $child->id], [
                                        'class' => 'btn btn-sm btn-primary',
                                        'data' => [
                                        ]
                                    ]); ?>
                                <?= Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['category/update', 'id' => $child->id], [
                                        'class' => 'btn btn-sm btn-success',
                                        'data' => [
                                        ]
                                    ]); ?>
                                <?= Html::a('<span class="glyphicon glyphicon-trash"></span>', ['category/delete', 'id' => $child->id], [
                                        'class' => 'btn btn-sm btn-danger',
                                        'data' => [
                                            'method' => 'post',
                                            'confirm' => 'Do you really want to delete this item?'
                                        ]
                                ]); ?>
                            </div>
                        </td>
                    </tr>
                    <?
                        $counter++;
                    ?>
                <? endforeach; ?>
            <? endforeach; ?>
        </tbody>
    </table>

</div>

modules/admin/views/category/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = 'Update Category: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="category-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/category/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Category */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Categories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="category-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'parent.name',
                'label' => 'Parent'
            ],
            'name',
            'status',
        ],
    ]) ?>

</div>